version: "3"

services:
  yaus:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:${POSTGRES_VERSION:-12}
    environment:
      POSTGRES_USER: ${DB_USERNAME:-yaus}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-urls}
    ports:
      - "${DB_HOST:-127.0.0.1}:${DB_PORT:-54321}:54321"
    command: ["postgres", "-c", "log_statement=all"]
