version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      YAUS_DB_URL: "postgres://yaus:postgres@db:5432/urls"
    depends_on:
      - db
  db:
    image: postgres:${POSTGRES_VERSION:-12}
    environment:
      POSTGRES_USER: ${DB_USERNAME:-yaus}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-urls}
    volumes:
    - ./devops/db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "${DB_HOST:-127.0.0.1}:${DB_PORT:-54321}:5432"
    command: ["postgres", "-c", "log_statement=all"]
