name: test
on: [push, pull_request]

jobs:
  lint:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Download mock generating tools
        run: make tools-generate
      - name: Run test
        run: make test